/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Form;

import Database.ClassDatabase;
import com.mysql.cj.jdbc.PreparedStatementWrapper;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.HashMap;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author AP
 */
public class FormEntriDataPembelian extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormEntriDataPembelian
     */
    public FormEntriDataPembelian() {
        initComponents();
        try{
    Connection c=ClassDatabase.getkoneksi();
    Statement s= c.createStatement();
    String sql="select id, no_beli, kode, j_beli, tgl_beli, kodesup from acc";
    ResultSet r=s.executeQuery(sql);
    TableAcc.setModel(DbUtils.resultSetToTableModel(r));
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Nopembelian = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Kode_Barang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Nama_Barang = new javax.swing.JLabel();
        Harga_Beli = new javax.swing.JLabel();
        Harga_Jual = new javax.swing.JLabel();
        Total_Stok = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Jumlah_Beli = new javax.swing.JTextField();
        Kode_Supplier = new javax.swing.JTextField();
        Tanggal_Pembelian = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        cariData = new javax.swing.JTextField();
        Nama_Supplier = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        SAVE = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableAcc = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        awala = new com.toedter.calendar.JDateChooser();
        akhira = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Form Entri Data Pemebelian ACC");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("No. Pembelian");

        Nopembelian.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                NopembelianCaretUpdate(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Kode Barang");

        Kode_Barang.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Kode_BarangCaretUpdate(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Nama Barang");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Harga Beli");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Harga Jual");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Total Stok");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Total_Stok)
                    .addComponent(Harga_Jual)
                    .addComponent(Harga_Beli)
                    .addComponent(Nama_Barang)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Nopembelian)
                        .addComponent(Kode_Barang, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nopembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Kode_Barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Nama_Barang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Harga_Beli))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Harga_Jual))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Total_Stok))
                .addGap(22, 22, 22))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Jumlah Beli");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Tanggal Pembelian");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Kode Supplier");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Nama Supplier");

        Kode_Supplier.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Kode_SupplierCaretUpdate(evt);
            }
        });

        jButton2.setText("Menampilkan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Kode_Supplier)
                                    .addComponent(Jumlah_Beli)
                                    .addComponent(Tanggal_Pembelian, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                            .addComponent(jLabel11)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nama_Supplier)
                            .addComponent(cariData))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(Jumlah_Beli, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(Tanggal_Pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Kode_Supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Nama_Supplier))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(cariData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        SAVE.setText("SAVE");
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });

        jButton3.setText("EDIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("CLOSE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SAVE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TableAcc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableAcc);

        jLabel12.setText("Tanggal Awal");

        jLabel13.setText("Tanggal Akhir");

        jButton6.setText("PRINT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(awala, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(akhira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(awala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(akhira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void resetinput(){
        this.Nopembelian.setText("");
        this.Kode_Barang.setText("");
        this.Jumlah_Beli.setText("");
        this.Kode_Supplier.setText("");
        this.Tanggal_Pembelian.setDate(null);
        this.Nama_Barang.setText("");
        this.Harga_Beli.setText("");
        this.Harga_Jual.setText("");
        this.Total_Stok.setText("");        
        this.Nama_Supplier.setText("");
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        resetinput();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String key = cariData.getText();
    if(cariData.getText().isEmpty()){
        try{
    Connection c=ClassDatabase.getkoneksi();
    Statement s= c.createStatement();
    String sql="select id, no_beli, kode, j_beli, tgl_beli, kodesup from acc";
    ResultSet r=s.executeQuery(sql);
    TableAcc.setModel(DbUtils.resultSetToTableModel(r));
}catch (SQLException e){
    JOptionPane.showMessageDialog(null, e);
}
    }else{
            try{
    Connection c=ClassDatabase.getkoneksi();
    Statement s= c.createStatement();
    String sql="select id, no_beli, kode, j_beli, tgl_beli, kodesup from acc WHERE kode LIKE '%"+key+"%' OR no_beli LIKE '%"+key+"%'"; 
    ResultSet r=s.executeQuery(sql);
    TableAcc.setModel(DbUtils.resultSetToTableModel(r));
}catch (SQLException e){
    JOptionPane.showMessageDialog(null, e);
}
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Kode_BarangCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Kode_BarangCaretUpdate
        // TODO add your handling code here:
        
         try{
            Connection c = ClassDatabase.getkoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM barang WHERE kodebarang = '" + this.Kode_Barang.getText() + "'";
            ResultSet r = s.executeQuery(sql);
            
            while(r.next()){
                this.Nama_Barang.setText(r.getString("namabarang"));
                this.Harga_Beli.setText(r.getString("h_beli"));
                this.Harga_Jual.setText(r.getString("h_jual"));
                this.Total_Stok.setText(r.getString("stok"));
            }
            r.close();
            s.close();
            
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_Kode_BarangCaretUpdate

    private void Kode_SupplierCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Kode_SupplierCaretUpdate
        // TODO add your handling code here:
        
         try{
            Connection c = ClassDatabase.getkoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM supplier WHERE kode = '" + this.Kode_Supplier.getText() + "'";
            ResultSet r = s.executeQuery(sql);
            
            while(r.next()){
             this.Nama_Supplier.setText(r.getString("nama"));
            }
            r.close();
            s.close();
            
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_Kode_SupplierCaretUpdate

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
        
       int id=0, saham1=0;
       java.util.Date tgl_beli = (java.util.Date) this.Tanggal_Pembelian.getDate();
       String no_beli = this.Nopembelian.getText();
       String kodea = this.Kode_Barang.getText();       
       String kodesup = this.Kode_Supplier.getText();
       int stoka1 = Integer.parseInt(Total_Stok.getText());
       int j_beli1 = Integer.parseInt(Jumlah_Beli.getText());
       int h_beli1 = Integer.parseInt(Harga_Beli.getText());
       
       stoka1 = stoka1 + j_beli1;
       
       saham1 = stoka1 * h_beli1;
              
       String h_belia = Harga_Beli.getText();
       Total_Stok.setText(Integer.toString(stoka1));
       Jumlah_Beli.setText(Integer.toString(j_beli1));
       String saham = Integer.toString(saham1);
       
       String stoka = this.Total_Stok.getText();
       String j_beli = this.Jumlah_Beli.getText();
       
       if(Nopembelian.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Data Belum Lengkap, Nomer Pembelian Tidak Boleh Kosong");           
       }else{
           if(Kode_Supplier.getText().isEmpty()){
               JOptionPane.showMessageDialog(null, "Data Belum Lengkap, Kode Supplier Tidak Boleh Kosong");
           }else{
               try{
                   Connection c = ClassDatabase.getkoneksi();
                   String sql = "INSERT INTO acc VALUES (?,?,?,?,?,?)";
                   PreparedStatement p = c.prepareStatement(sql);
                   p.setInt(1, id);
                   p.setString(2, no_beli);
                   p.setString(3, kodea);
                   p.setString(4, j_beli);
                   p.setDate(5, new java.sql.Date(tgl_beli.getTime()));
                   p.setString(6, kodesup);
                   p.executeUpdate();
                   p.close();
                   JOptionPane.showMessageDialog(null, "Sukses Tambah Data");
                   
                   
              }catch(Exception e){
                   System.out.println(e);
              }
           }
       }
          try{
    Connection c=ClassDatabase.getkoneksi();
    Statement s= c.createStatement();
    String sql="select id, no_beli, kode, j_beli, tgl_beli, kodesup from acc";
    ResultSet r=s.executeQuery(sql);
    TableAcc.setModel(DbUtils.resultSetToTableModel(r));
}catch (SQLException e){
    JOptionPane.showMessageDialog(null, e);
}
          
              try{
    Connection c=ClassDatabase.getkoneksi();
    
    String sql="UPDATE barang SET stok = ?, saham = ? WHERE kodebarang = ?";
    PreparedStatement p = c.prepareStatement(sql);
    p.setString(1, stoka);
    p.setString(2, saham);
    p.setString(3, kodea);
    p.executeUpdate();
    p.close();
}catch (SQLException e){
    JOptionPane.showMessageDialog(null, "di update : "+e);
}
              resetinput();
       
    }//GEN-LAST:event_SAVEActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        
         String kode = Nopembelian.getText();
         int stok_dihapus = 0;
         int total_stok = 0;
           try{
    Connection c=ClassDatabase.getkoneksi();
    Statement s= c.createStatement();
    String sql="SELECT * FROM acc WHERE no_beli ='" + this.Nopembelian.getText()+"'";
    ResultSet r=s.executeQuery(sql);
            while(r.next()){
                 stok_dihapus = Integer.parseInt(r.getString("j_beli"));
            }
            
     sql="SELECT * FROM barang where kodebarang ='" + this.Kode_Barang.getText()+"'";
      r=s.executeQuery(sql);
            while(r.next()){
                 total_stok = Integer.parseInt(r.getString("stok"));
            }
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
           
           total_stok -= stok_dihapus;
           

              try{
                Connection c = ClassDatabase.getkoneksi();
                String sql = "UPDATE barang SET stok = ? WHERE kodebarang= ?";
                PreparedStatement p = (PreparedStatement) c.prepareStatement(sql);                                                    
                p.setString(1, Integer.toString(total_stok));
                p.setString(2, Kode_Barang.getText());
                p.executeUpdate();
                p.close();                
                          
                      }catch(Exception e){
                          System.out.println(e);
                      }
             try{
                Connection c = ClassDatabase.getkoneksi();
                String sql = "DELETE FROM acc WHERE no_beli = ?";
                PreparedStatement p = (PreparedStatement) c.prepareStatement(sql);                                                    
                p.setString(1, kode);                        
                p.executeUpdate();
                p.close();
                JOptionPane.showMessageDialog(this, "Data Sukses Di Hapus");
                          
                      }catch(Exception e){
                          System.out.println(e);
                      }
             
             
                 try{
    Connection c=ClassDatabase.getkoneksi();
    Statement s= c.createStatement();
    String sql="select id, no_beli, kode, j_beli, tgl_beli, kodesup from acc";
    ResultSet r=s.executeQuery(sql);
    TableAcc.setModel(DbUtils.resultSetToTableModel(r));
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
             

             resetinput();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void NopembelianCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_NopembelianCaretUpdate
        
         try{
            Connection c = ClassDatabase.getkoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM acc WHERE no_beli = '" + this.Nopembelian.getText()+ "'";
            ResultSet r = s.executeQuery(sql);
            
            while(r.next()){
                this.Kode_Barang.setText(r.getString("kode"));
                this.Jumlah_Beli.setText(r.getString("j_beli"));
                this.Tanggal_Pembelian.setDate(r.getDate("tgl_Beli"));
                this.Kode_Supplier.setText(r.getString("kodesup"));
                
            }
            r.close();
            s.close();
            
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_NopembelianCaretUpdate

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
       int id=0, saham1=0;
        int j_beli_awal = 0;
       java.util.Date tgl_beli = (java.util.Date) this.Tanggal_Pembelian.getDate();
       String no_beli = this.Nopembelian.getText();
       String kodea = this.Kode_Barang.getText();       
       String kodesup = this.Kode_Supplier.getText();
       int stoka1 = Integer.parseInt(Total_Stok.getText());
       int j_beli1 = Integer.parseInt(Jumlah_Beli.getText());
       int h_beli1 = Integer.parseInt(Harga_Beli.getText());
       try{
    Connection c=ClassDatabase.getkoneksi();
    Statement s= c.createStatement();
    String sql="SELECT * FROM acc where no_beli ='" + this.Nopembelian.getText()+"'";
    ResultSet r=s.executeQuery(sql);
        while(r.next()){
             j_beli_awal = Integer.parseInt(r.getString("j_beli"));
            
        }
}catch (SQLException e){
    JOptionPane.showMessageDialog(null, e);
}
          
      stoka1-=j_beli_awal;
      stoka1 += j_beli1;
      
       String h_belia = Harga_Beli.getText();       
       String saham = Integer.toString(saham1);
       
       String stoka = this.Total_Stok.getText();
       String j_beli = this.Jumlah_Beli.getText();
       
      if(Nopembelian.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Data Belum Lengkap, Nomer Pembelian Tidak Boleh Kosong");           
       }else{
           if(Kode_Supplier.getText().isEmpty()){
               JOptionPane.showMessageDialog(null, "Data Belum Lengkap, Kode Supplier Tidak Boleh Kosong");
           }else{
               try{
                   Connection c = ClassDatabase.getkoneksi();
                   String sql = "UPDATE acc SET kode = ?, j_beli = ?, tgl_beli = ?, kodesup = ? WHERE no_beli = ?";
                   PreparedStatement p = c.prepareStatement(sql);
                   p.setString(1, kodea);
                   p.setString(2, Integer.toString(j_beli1));
                   p.setDate(3, new java.sql.Date(tgl_beli.getTime()));
                   p.setString(4, kodesup);
                   p.setString(5, no_beli);

                   p.executeUpdate();
                   p.close();
                   JOptionPane.showMessageDialog(null, "Sukses Diubah");
                   
                   
              }catch(Exception e){
                   System.out.println(e);
              }
           }
       }
          try{
    Connection c=ClassDatabase.getkoneksi();
    Statement s= c.createStatement();
    String sql="select id, no_beli, kode, j_beli, tgl_beli, kodesup from acc";
    ResultSet r=s.executeQuery(sql);
    TableAcc.setModel(DbUtils.resultSetToTableModel(r));
}catch (SQLException e){
    JOptionPane.showMessageDialog(null, e);
}
          
              try{
    Connection c=ClassDatabase.getkoneksi();
    
    String sql="UPDATE barang SET stok = ?, saham = ? WHERE kodebarang = ?";
    PreparedStatement p = c.prepareStatement(sql);
    p.setString(1, Integer.toString(stoka1));
    p.setString(2, saham);
    p.setString(3, kodea);
    p.executeUpdate();
    p.close();
}catch (SQLException e){
    JOptionPane.showMessageDialog(null, "di update : "+e);
}
              resetinput();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
           int ex = JOptionPane.showConfirmDialog(null, "Apakah anda akan keluar?", "Anda yakin?",JOptionPane.YES_NO_OPTION);        
        if(ex == 0){
            dispose();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
          try{
         Connection c=ClassDatabase.getkoneksi();                
         HashMap <String, Object> parameters = new HashMap<>();
         parameters.put("awal", awala.getDate());
         parameters.put("akhir", akhira.getDate());
        String pathReport ="src/report/report_DatePembelian.jasper";  
        JasperPrint print = JasperFillManager.fillReport(pathReport, parameters,c);
        JasperViewer viewer = new JasperViewer(print, false);
        viewer.setVisible(true);
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Harga_Beli;
    private javax.swing.JLabel Harga_Jual;
    private javax.swing.JTextField Jumlah_Beli;
    private javax.swing.JTextField Kode_Barang;
    private javax.swing.JTextField Kode_Supplier;
    private javax.swing.JLabel Nama_Barang;
    private javax.swing.JLabel Nama_Supplier;
    private javax.swing.JTextField Nopembelian;
    private javax.swing.JButton SAVE;
    private javax.swing.JTable TableAcc;
    private com.toedter.calendar.JDateChooser Tanggal_Pembelian;
    private javax.swing.JLabel Total_Stok;
    private com.toedter.calendar.JDateChooser akhira;
    private com.toedter.calendar.JDateChooser awala;
    private javax.swing.JTextField cariData;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
